# Generated by Django 5.0.3 on 2025-03-29 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friendrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='upi_id',
        ),
    ]
