# Generated by Django 5.0.3 on 2025-03-14 05:39

import django.db.models.deletion
import embed_video.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Egit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egit_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Foo_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_photo', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('name', models.CharField(max_length=200)),
                ('normal_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('premium_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('foo_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.foo_category')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.cart')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menuitems')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='core.CartItem', to='core.menuitems'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=1000, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('in_process', 'In Process'), ('done', 'Done')], default='in_process', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_pay', models.CharField(default='PENDING', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='core.order'),
        ),
        migrations.CreateModel(
            name='Staller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=400)),
                ('video', embed_video.fields.EmbedVideoField(null=True)),
                ('contact', models.CharField(default='1234', max_length=12)),
                ('timings', models.CharField(max_length=14)),
                ('rating', models.FloatField(default=0)),
                ('keywords', models.CharField(default='spicy', max_length=1000, null=True)),
                ('payr', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('rush', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('category', models.ManyToManyField(related_name='categor', to='core.category')),
                ('egit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.egit')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slider_images', models.ManyToManyField(blank=True, related_name='stallers', to='core.sliderimage')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='stall_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staller'),
        ),
        migrations.CreateModel(
            name='New_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('offer_photo', models.ImageField(upload_to='static/images/offer_pics/')),
                ('message', models.CharField(max_length=10000)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.staller')),
            ],
        ),
        migrations.AddField(
            model_name='menuitems',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.staller'),
        ),
        migrations.AddField(
            model_name='foo_category',
            name='sh_owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.staller'),
        ),
        migrations.AddField(
            model_name='cart',
            name='related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.staller'),
        ),
        migrations.CreateModel(
            name='Subcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(blank=True, max_length=30, null=True)),
                ('sub_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.AddField(
            model_name='staller',
            name='loc_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subcat'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FooRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foo_ratings', to='core.menuitems')),
            ],
            options={
                'unique_together': {('user', 'menu')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('staller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.staller')),
            ],
            options={
                'unique_together': {('user', 'staller')},
            },
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('staller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='core.staller')),
            ],
            options={
                'unique_together': {('user', 'staller')},
            },
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'staller')},
            },
        ),
    ]
