# Generated by Django 5.0.3 on 2025-03-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staller',
            name='slider_images',
        ),
        migrations.DeleteModel(
            name='SliderImage',
        ),
    ]
