# Generated by Django 5.0.3 on 2025-03-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_staller_slider_images_delete_sliderimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staller',
            name='payr',
        ),
    ]
