# Generated by Django 5.0.3 on 2025-03-29 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_loccat_remove_staller_loc_cat_remove_staller_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staller',
            name='loc_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.loccat'),
        ),
    ]
